#!/bin/sh
# get [zip]
dir="`dirname $0`/.."
case `uname -s` in
  CYGWIN* ) 
    java -cp "$dir/class;$dir/lib/gson-2.1.jar" edu.wpi.always.weather.WeatherJsonParser "$1"
    ;;
  *)
    java -cp "$dir/class:$dir/lib/gson-2.1.jar" edu.wpi.always.weather.WeatherJsonParser "$1"
    ;;
esac
