#!/bin/sh 

start() {
   # sudo /home/reeti/Always-On/always/core/Reeti/CapturingRestarter/restartCaptureServer.sh
   export LD_LIBRARY_PATH="/usr/local/gostai/lib"

   until /home/reeti/Always-On/always/core/Reeti/build/src/ReetiServer_Capturing 192.168.1.1 27017; do
      echo "Server crashed with exit code $?. Respawning..." >&2
      sleep 1
   done
}

stop() {
   sudo pkill ReetiServer_Cap
}

restart() {
   stop
   start
}

status() {
   echo "ReetiServer_Cap Process:"
   pgrep ReetiServer_Cap
}

case "$1" in
start)
	start
;;
stop)
	stop
;;
restart)
	restart
;;
status)
	status
;;
*)

echo $"Usage: $0 {start|stop|restart|status}"

exit 1

esac

exit $RETVAL
